### ISSUE TITLE
Different fork violating WinDirStat’s license

### ISSUE THREAD

**Issue by nitz** [windirstat/windirstat#43]
I had recently come across the fork “Fast WinDirStat” that implements using the NTFS MFT to enable faster scanning of disks. As I went to learn how it was accomplished, in hopes that I might contribute something similar back here. I then discovered that the source code they publish is not the entire project, thus violating the GPL v2.

I submitted [an issue](https://github.com/thradde/FastWinDirStat/issues/4) to ask for the remaining source as per the GPL’s requirements, but was told that the modules that are [included in the binary distribution](https://www.idealsoftware.com/opensource/Fast%20WinDirStat%20Setup.exe) (via [this page](https://www.idealsoftware.com/opensource/fast-windirstat.html)) weren’t subject to the GPL. I am aware that the FSF’s [views on what it means to link to a program](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#FSWithNFLibs) are more liberal than most, so perhaps that author’s assertion that the other application distributed with their fork isn’t required to be licensed under the GPL v2; IANAL so that argument is outside of my arena. However I do know that dynamically linked binaries _are_ required to be GPL v2 licensed, and the author [seems like they are unwilling to follow the license terms](https://github.com/thradde/FastWinDirStat/issues/4#issuecomment-2051011131).

---

As per the [guidelines for reporting a GPL violation](https://www.gnu.org/licenses/gpl-violation.html), here are the details they specifically look for:

- Does the distribution contain a copy of the License?
  - Yes. The source distribution includes license.txt in [the same way the upstream project does](https://github.com/thradde/FastWinDirStat/blob/master/make/windirstat/res/license.txt ). As well, the [binary distribution](https://www.idealsoftware.com/opensource/Fast%20WinDirStat%20Setup.exe) does, presents the GPL v2 (and no other license) in the installer.
- Does it clearly state which software is covered by the License? Does it say anything misleading, perhaps giving the impression that something is covered by the License when in fact it is not?
  - Yes. The binary distribution includes _only_ the GPL v2, which is agreed to through the installer. As this was the first I had encountered this program, it wasn’t until later that it was pointed out to me that the fork’s repository readme includes text that says that it relies on a non-free component.
- Is source code included in the distribution?
  - No. The binary distribution includes no source whatsoever.
- Is a written offer for source code included with a distribution of just binaries?
  - No, outside of the text of the license itself.
- Is the available source code complete, or is it designed for linking in other nonfree modules?
  - No. It is written to dynamically link to a nonfree module (COGNOSAPI.dll), which then somehow interacts with another nonfree module (CognosNT.exe). Both nonfree modules are distributed with the other fork binaries.

- the precise name of the product
  - “Fast WinDirStat”
- the name of the person or organization distributing it
  - “IDEAL Software GmbH”. I am unaware of the exact link between GitHub user thradde is and IDEAL Software GmbH, but no binaries are distributed through GitHub
- email addresses, postal addresses and phone numbers for how to contact the distributor(s)
  - As listed on [their contact page](https://www.idealsoftware.com/en/contact.html), their email address is support@IdealSoftware.com, and phone number +49 (0)2131 1511-690. I have not seen a published address.
- the exact name of the package whose license is violated
  - “WinDirStat” (https://github.com/windirstat/windirstat)
- how the license was violated:
  - Is the copyright notice of the copyright holder included?
    - Yes, the copyright information in the about window and in the available source files is intact.
  - Is the source code completely missing?
    - No.
  - Is there a written offer for source that's incomplete in some way? This could happen if it -provides a contact address or network URL that's somehow incorrect.
    - No.
  - Is there a copy of the license included in the distribution?
    - Yes.
  - Is some of the source available, but not all? If so, what parts are missing?
    - The source for the primary application is available, but two included/linked nonfree components is not available.

Edit to add: I have [reported this violation to the FSF](https://www.gnu.org/licenses/gpl-violation.html)

**Comment by NoMoreFood** [comment]
@nitz Thanks for being a good open source steward.  I'll defer to @assarbad for his thoughts on this one.

**Comment by assarbad** [comment]
Hey folks, I agree with the assertion that the DLL side interfacing with the service should abide by the GPL as required. However, don't get your hopes up, because I think that's it right there. _Maybe_ the dev will even do it to comply to the GPL, especially if we really push for it. But it's still not going to show the workings of what the service does under the hood (which would be the interesting part). The most anyone could hope for is that the `COGNOSAPI.dll` would become open source.

@nitz thanks first of all for bringing that to our attention.

There was a comment on a blog post which announced the migration from Bitbucket to OSDN. Alas, OSDN itself is now history as well, _so the blog post was withdrawn_. [You can still find it, however](https://web.archive.org/web/20230131031155/https://blog.windirstat.net/20200711/migration-off-of-bitbucket/).

Given the temporal proximity of the comment exchange and the first commit to the "fork", as well as other indicators we can probably assume that the same person is behind the comments and the "fork".

Relevant excerpt from the exchange of comments (emphasis mine):

> I developed a library to read the file structure of NTFS drives within a few seconds. Much faster than using stat() et al. For a hard drive with about 900.000 files and directories, it requires 10 seconds to read the whole directory tree, compared to 5 minutes, when using the standard Windows API. **I am willing to provide a free license to this project, just contact me.**

At the time this sounded to me as if someone was attempting to plug their product. Nothing wrong with that, but I told him that there was no interest, essentially trying to convey that the project was under GPL and there was no intent to waver regarding the commitment to the GPL.

I also mentioned there are solutions similar to his which are FLOSS (albeit under more liberal licenses than the GPL, [notably this one](https://www.codeproject.com/Articles/81456/An-NTFS-Parser-Lib)) and why they weren't chosen (MFT parsing requires privileges). A few months later he responded:

> Regarding my fast NTFS processing tool, I did not recognize you are answering here. I rather had thought you reply by e-mail. Just for clarification: WDS would not require administrative permissions, because my tool runs as a service and communicates with the DLL; which in turn provides a simple API equal to FindFirstFile() / FindNextFile(). The discussion about closed source is in this case somewhat strange, because you also call FindFirstFile() / FindNextFile() in kernel32.dll, which is closed source.
> Regarding your concerns about correct parsing of the MFT, my test software compares the results against FindFirstFile() / FindNextFile() and does not show any discrepancies.

Of course this clarified the absence of a need to have elevated privileges when running WinDirStat. Although they'd still be needed to install a service into the TCB. I responded (excerpt, emphasis added):

>  It’s a system interface. The difference is that you propose to bundle your proprietary components — evidently there’s a service plus a DLL, as you can see from my response I was assuming solely a DLL (although a service explains how you manage to read the MFT, since this would require privileges) — with a GPL’d software. If you’re unaware of the implications of that, let me briefly state: bad idea.
> 
> **Feel free to fork WDS for your purpose to include your library, but be prepared that people may start asking for the source of your DLL (and possibly the service).**

The last part is of particular interest.

Now, the thing is that [the repo in question](https://github.com/thradde/FastWinDirStat) wasn't even created as a fork. Because _then_ we could have stumbled over it by accident when looking at [the network graph of forks](https://github.com/windirstat/windirstat/network). It's a "clean" check-in of some version (not exactly specified, perhaps the zipped one?) and then some commits on top.

Now, as far as _not forking_ is concerned, nothing in the GPL violated there. No one says you have to reuse the exact version history, although it's usually deemed bad form.

Even bundling the proprietary DLL with the GPL'd code may not have constituted a violation of the GPL if certain preconditions had been met. One would be to create a new piece of source under LGPL that interfaces _with_ the proprietary DLL. As far as I can tell, sifting through the commits on top, the files in question are:

* [CogFileFind.cpp](https://github.com/thradde/FastWinDirStat/blob/master/make/windirstat/CogFileFind.cpp)
* [CogFileFind.h](https://github.com/thradde/FastWinDirStat/blob/master/make/windirstat/CogFileFind.h)

... they include no file header or mention of the license. But going strictly by the terms of the GPLv2 this means because that code is _linked_ into the resulting binary, every recipient of the binary is allowed to get this source. Fair enough, that's possible. The missing file header is merely bad form at this point. These two files are still subject to the GPL. The clever method would have been to place these two files under LGPL, then the dynamic linking with that proprietary DLL -- to the best of my understanding -- would no longer be an issue of the GPL (_without_ the L in front of the G).

_However_ as @nitz correctly pointed out, the dynamic linking to the DLL constitutes a violation of the GPL to the best of my understanding. Because even though these aforementioned source files provide an abstraction layer -- presumably meant to shield from the effect of the GPL -- the author is mistaken that this poses "no problem" (first response in thradde/FastWinDirStat#4). It does _pose_ a problem, _because_ these files are implicitly under GPL. And in fact at this point with these versions of "Fast WinDirStat" in circulation anyone receiving the bundled DLL can probably lay claim to receive its source _under the terms of the GPLv2_ on account of that. As I mentioned at the beginning, that's not a big win. Heck, the author could probably even dual-license the DLL provided there is "nothing to hide" (thinking handling of the serial numbers here) under their own proprietary license _and_ the GPL and get away with it.

However, the bundling of the service -- take that with a few spoonful of salt, IANAL and anyway three lawyers five opinions -- will probably not suffice to make it subject to the GPL as far as I understand it. The DLL, yes. The service `.exe`, unfortunately not.

Making two installers as commented [here](https://github.com/thradde/FastWinDirStat/issues/4#issuecomment-2062206754) in thradde/FastWinDirStat#4 would probably have resolved the issue if done initially. But technically the genie is out of the bottle -- i.e. the binary has been released (and the repo [exists now also as a fork](https://github.com/assarbad/FastWinDirStat) and [the issue is archived](https://web.archive.org/web/20240423220306/https://github.com/thradde/FastWinDirStat/issues/4)) -- so _technically_ any recipient of the _existing_ bundle is entitled to receiving the source of the DLL under the GPL.

Hope this clarifies it. I'll send an email to WinDirStat's original author (CCing you @NoMoreFood) to ask his opinion, but quite frankly I don't see much sense in pushing this. True, technically right is the Best Version of Right™ 😜, but given the GPL the most we could reasonably hope for is forcing the DLL under GPL (and yes, it would have to be that exact version of the DLL, no ifs no buts ... possibly including some actual trade secrets). But what's the point of that? The interesting parts would be in the service and at that point I'm sure _some_ lawyer _would_ be willing to represent the case that the bundling subjects the service _also_ to the GPL, but I doubt that this stands a chance in court, given the wording of the GPLv2 and their FAQ.

Oliver

**Disclaimer:** all these things above are as far as I understand them. a.) IANAL, b.) I am in the same jurisdiction as [@thradde](https://github.com/thradde) so our understanding of legal concepts is probably somewhat similar.

**Comment by nitz** [comment]
I appreciate the thorough investigation and explanations, Oliver! Especially the bits about the earlier proposals.

Your conclusions mostly mirror my current understanding.

> Fair enough, that's possible. The missing file header is merely bad form at this point. 

The header file being distributed separately from the same location as the binary distribution feels like another intentional GPL snub to me, but I'll yield that opinion may come from me just being cynical. 

>  but quite frankly I don't see much sense in pushing this. True, technically right is the Best Version of Right™ 😜,

This has been basically my assumption from the beginning, to be candid. It rubs me the wrong way that @thradde seemed to want to have their cake and eat it too. I think it's a very cool thing to make an addition to a GPL'd project to promote your own work. I'd argue that it's another thing entirely to do so with no intent to make your contributions available to the community likewise. Even if it was done in a way that violated the license, I'd argue that it still violates the spirit of it. To my eye as an outsider, it seems an attempt to leverage the work of the WinDirStat team (and name,) with little to no intention to benefit the community as a whole — something that's [against the heart of what the GPL was created for](https://www.gnu.org/philosophy/pragmatic.html).

I personally find the GPL terms incredibly restrictive, and as such tend to try and release the code I can under licenses that are as permissive as possible. However: the ideals of the GPL is something I _do_ feel very strongly about, and loathe when a party seeks to actively combat its goals. Or perhaps I'm just getting more curmudgeoney as I age. 🤷‍♀️

**Comment by assarbad** [comment]
> The header file being distributed separately from the same location as the binary distribution feels like another intentional GPL snub to me, but I'll yield that opinion may come from me just being cynical.

@nitz I noticed _that_, too. Doubt it's due to cynicism _alone_.

> I think it's a very cool thing to make an addition to a GPL'd project to promote your own work. I'd argue that it's another thing entirely to do so with no intent to make your contributions available to the community likewise. Even if it was done in a way that did not violate the license, I'd argue that it still violates the spirit of it. To my eye as an outsider, it seems an attempt to leverage the work of the WinDirStat team (and name,) with little to no intention to benefit the community as a whole — something that's [against the heart of what the GPL was created for](https://www.gnu.org/philosophy/pragmatic.html).

Definitely. Ironically he also leaned on the [philosophy argument (first paragraph in this comment)](https://github.com/thradde/FastWinDirStat/issues/4#issuecomment-2062206754). And I think that's another point where he got it wrong. I attended a talk by RMS several years back and if anything can be said then that he's dogmatic about his views regarding the ideas behind the GPL.

In fact when I wrote the original response, that was my feeling as well. Someone promoting their product without following the spirit of the GPL.

> I personally find the GPL terms incredibly restrictive, and as such tend to try and release the code I can under licenses that are as permissive as possible. However: the ideals of the GPL is something I _do_ feel very strongly about, and loathe when a party seeks to actively combat its goals. Or perhaps I'm just getting more curmudgeoney as I age. 🤷‍♀️

Same here ... I mean that _whole_ paragraph rings true for me 😁

Let's wait for Bernhard's response.

Oliver

PS: I don't know all the details and I am not really interested in reverse-engineering this stuff either, I just know from my work on an AV product that there's a lot one can get wrong when having a privileged service doing stuff on behalf of the user. For example any unprivileged user allowed to talk to that service might also be able to see all the contents of folders that are normally out of reach (names and other metadata). That creates some real issues and would be another reason not to use anything proprietary where at most we could ask the author how it works under the hood (or reverse engineer stuff, which in turn may make _us_ liable).

**Comment by assarbad** [comment]
No response. Let's close it. If we change our minds we can still reopen or create a new ticket.
