### ISSUE TITLE
Open Call For Testers

### ISSUE THREAD

**Issue by NoMoreFood** [windirstat/windirstat#6]
This issue is to identify folks that would be willing to test release candidates.  If you could potentially help, please make a comment here and we'll tag you when something is available.

**Comment by tron2k** [comment]
I could support you.

**Comment by theonlyames** [comment]
I honestly didn't think windirstat was actively developed any more and was looking for the code to create my own fork, so I'm interested in testing.

**Comment by Anutrix** [comment]
I am interested in testing and development too.

**Comment by vittoso** [comment]
I'm interested in testing, as well

**Comment by PEERSOFTdev** [comment]
Hello,
I am unable to build it myself on Windows 11 so will be very grateful to receive **any** binary to test, whether alpha, beta, RC etc. I will do my best to make the Czech localization current as well.

**Comment by NoMoreFood** [comment]
@PEERSOFTdev and others,

The latest build can be found here: https://github.com/windirstat/windirstat-next/releases/tag/Release_1_3_0_2024_03_17

To test any location changes, you can download the Czech localization text file: 

https://github.com/windirstat/windirstat/blob/master/windirstat/res/langs/lang_cz.txt

And put it in the same directory as WinDirStat.exe.  This will cause WinDirStat to override the embedded version with the local version of the file (so you do not need to compile to test changes).  There may be one or two strings in the English version (https://github.com/windirstat/windirstat/blob/master/windirstat/res/langs/lang_en.txt) that need to be defined yet in lang_cz.txt.  For example, IDS_MENU_FILE_SAVE_RESULTS and IDS_MENU_FILE_LOAD_RESULTS.

**Comment by PEERSOFTdev** [comment]
Hello Bryan,

Thanks for the alpha version. I could test it just briefly as my system allowed. I have observed the following behaviour so far:

  1.  The lang_cz.txt file seems to not being used when put along any of the executables. I tried to modify it and none of the changes appeared. The file has some accented letters replaced by the ASCII counterparts, e.g. „ě“ for „e“, „ř“ for „r“. The stable version does have them correct. It would be fine if you could get them to this version from the stable version, otherwise tell me and I will correct them manuály, however, if the same issue appeared in the help file then the corrections would involve probably much more time.
  2.  When I try to run this version against my C: drive, what appears OK in the stable version, the final user interface briefly shows (my Screen Reader tells me I am in a list where the folder tree should probably appear), then nothing happens from my perspective and when I then switch e.g. to the Start Menu and back by pressing the Windows key, Windows pops up a message that the application is not responding and whether I should wait for it to respond or kill it. If I let it wait, nothing appears even after 5 minutes. When I tried to select my D: drive with lots of files and folders too, I see the progress bar (my Screen Reader beeps for every percent) and then the final list appears and I can browse it. However, as soon as I expand a node where I expect lots of files and folders the program freezes again when it stops responding. I could observe the same behaviour with both NVDA and Narrator Screen Readers.
  3.  When I activated the portable mode in Settings and then tried to close the application, a message box appeared with the title „WinDirStat“ and message „Encountered an improper argument.“.

Best regards,

Petr Řehák

**Comment by NoMoreFood** [comment]
@PEERSOFTdev I will look into these.  Time permitting, can you open up a separate issue and delete your comment here so I can track it separately?

**Comment by Anutrix** [comment]
Tried the x64 executable on a 2TB SSD with 2 partitions.
First run took 18 seconds.
Second run took 4 seconds.
![image](https://github.com/windirstat/windirstat/assets/11459028/bd1e78de-4983-479f-b237-834b5680e974)
1.3 million files.

**Comment by NoMoreFood** [comment]
@Anutrix The timing sounds about right. The OS / drive caches some of the data that WinDirStat queries so subsequent runs are typically faster for awhile while everything is in-cache.

As for the "hangs", that's a consequence of the overhead of expanding and collapsing nodes in the UI.  I'll see if I can speed it up.  I am waiting for the new version of Visual Studio to fix an MFC profiling bug so that should help with tracking down performing issues.  Thanks for the feedback! Please open a new issue for anything substantial you find.  Thanks!

**Comment by NoMoreFood** [comment]
New build has been posted to address a crash when to attempting to delete files the user did not have permission to (or other common causes for deletion failing):

https://github.com/windirstat/windirstat-next/releases

**Comment by NoMoreFood** [comment]
@Anutrix, @PEERSOFTdev, @vittoso @theonlyames, @tron2k 

Another new alpha release posted. At this point, I'm done making scale changes and entering the "working out bugs" phase. Please let me know if you see anything or whether it looks good.  Thanks for any feedback thus far and in the future.

https://github.com/windirstat/windirstat-next/releases
