### ISSUE TITLE
[WinDirStat 2024-08-29] Automatic download of cloud files notification while doing a simple scan

### ISSUE THREAD

**Issue by vittoso** [windirstat/windirstat#82]
Hi,
I am trying beta version 2024-08-29 and I saw that, as soon as I start scanning the C: drive, I have a Windows 11 notification about automatic download of cloud files (i .e https://support.microsoft.com/en-us/windows/automatic-file-download-notifications-in-windows-dc73c9c9-1b4c-a8b7-8d8b-b471736bb5a0).

What is the cause of this? 
Is it downloading cloud files from OneDrive that were not already present in local drive? (If this is the cause, I don't think a simple scan of an hard drive should trigger the download of - potentially - loads of files.)

Is the cancellation of the automatic donwload supported?  If I cancel the download via Windows notification, it seems that WinDirStats goes in a not-responding state.

**Comment by assarbad** [comment]
I haven't looked at the latest code changes, but I know that cloud files have their own (official Win32) API and ntdll.dll also comes with a handful of `Rtl*` functions allowing to distinguish placeholder entries and determine their hydration state.

The latter functions are undocumented, but not hard to find or reverse engineer or understand. They allow checking a value that is synthesized by the FS driver when enumerating and AFAIK applications are encouraged to honor the dehydrated state and avoid hydration. However, I recall there were some shims you could apply to WinDirStat as a temporary workaround. Microsoft introduced these because some old applications naturally wouldn't have any idea of cloud files.

Seems like something in the version triggers hydration of the files. My guess would be that WDS traverses into a directory that isn't hydrated and queries data points such as timestamps or file sizes etc. As long as it doesn't perform actual read of content the hydration should still remain partial (only metadata), but it depends a little on the cloud provider and its implementation, too. The best would be an option to ignore cloud placeholders by default and enable that on demand. It's somewhat akin to ignoring particular types of reparse points or handling sparse files differently.

PS: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtliscloudfilesplaceholder and https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlispartialplaceholder and some others are the functions in ntdll.dll

**Comment by NoMoreFood** [comment]
Yeah, I wouldn't have expected this unless you are doing duplicate detection.  I use OneDrive at work so I will see I can reproduce this.

**Comment by vittoso** [comment]
I don't think version WinDirStat-2.0.0-2024-07-22 did this, but I'll check again when possible.

**Comment by vittoso** [comment]
Hi @NoMoreFood I cannot see the Windows 11 notification about automatic download of cloud files when using the latest beta. 
Thanks!
