### ISSUE TITLE
[Beta Question] Does it use the MFT now?

### ISSUE THREAD

**Issue by jamesaepp** [windirstat/windirstat#94]
Version 2.0.0.0 (2024-10-10).

First - thanks to the volunteers keeping this project alive. I had started to believe it would slip into the annals of history but was pleasantly surprised to see a new beta being worked on.

My first impression is that it is a lot faster than the previous/stable/legacy/1.x version. Out of curiosity, does the beta version now make use of the MFT to sequentially read the entire filesystem in one go like TreeSize/Wiztree/other software does with greater efficiency?

**Comment by assarbad** [comment]
It does not. Reading the MFT requires extra privileges active at all times and the result only works for NTFS. So it was never a first choice. The new code uses NT native functions instead of the 

You can consult [`FileFind.cpp`](https://github.com/windirstat/windirstat/blob/master/windirstat/FileFind.cpp) for the details.

**Comment by NoMoreFood** [comment]
I _may_ consider adding MFT reading support in the future, but I'm pretty happy with where we are performance wise with the file system agnostic approach.

**Comment by berkayfeci** [comment]
Optional MFT support would be great, always great to have extra options and not having to use WizTree would be great.
